name: Tests

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

      # --- dependency installation ---
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - name: Load cached venv if cache exists
      id: cached-poetry-dependencies
      uses: actions/cache@v2
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
    - name: Install dependencies if cache miss
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      run: poetry install --no-interaction --no-root
    - name: Install root project
      run: poetry install --no-interaction

      # --- tests ---
    - name: Unit tests and coverage report
      run: |
        source .venv/bin/activate
        python manage.py migrate
        coverage run manage.py test
        coverage report -m --skip-empty --skip-covered
    - name: mypy
      run: |
        source .venv/bin/activate
        mypy --ignore-missing-imports $(git ls-files '*.py' | grep -v migrations/ | grep -v /apps.py)
    - name: pyright (via ReviewDog)
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        source .venv/bin/activate
        npm install pyright
        BASE_PATH="$(cd "$(dirname "$0")" && pwd)"
        cd "${GITHUB_WORKSPACE}/${INPUT_WORKDIR}" || exit 1
        TEMP_PATH="$(mktemp -d)"
        PATH="${TEMP_PATH}:$PATH"

        echo '::group::🐶 Installing reviewdog ... https://github.com/reviewdog/reviewdog'
        curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s -- -b "${TEMP_PATH}" "${REVIEWDOG_VERSION}" 2>&1
        echo '::endgroup::'

        echo '::group::🐍 Installing pyright ...'
        npm install pyright
        echo '::endgroup::'

        echo '::group::🔎 Running pyright with reviewdog 🐶 ...'
        "$(npm bin)/pyright" --outputjson |
          python3 .github/workflows/pyright_to_rdjson.py  |
          reviewdog -f=rdjson -name="pyright-report" \
            -reporter="github-check" \
            -fail-on-error="true"
        reviewdog_rc=$?
        echo '::endgroup::'
        exit $reviewdog_rc

  style:
    name: pyflakes and yapf
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup Python
        uses: actions/setup-python@v2
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip
          restore-keys: ${{ runner.os }}-pip
      - name: Install PyFlakes + TOML + YAPF
        run: |
          python -m pip install --upgrade pyflakes toml yapf
      - name: Run Pyflakes
        run: |
          pyflakes .
      - name: Run YAPF
        run: |
          yapf $(git ls-files '*.py' | grep -v migrations/ | grep -v /apps.py)
